// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}




// Validate ../../app/api/ai-reply/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-reply">> = Specific
  const handler = {} as typeof import("../../app/api/ai-reply/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/books/[bookId]/assistant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/books/[bookId]/assistant">> = Specific
  const handler = {} as typeof import("../../app/api/books/[bookId]/assistant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/books/[bookId]/chapter-memory/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/books/[bookId]/chapter-memory">> = Specific
  const handler = {} as typeof import("../../app/api/books/[bookId]/chapter-memory/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/books/[bookId]/prompted-notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/books/[bookId]/prompted-notes">> = Specific
  const handler = {} as typeof import("../../app/api/books/[bookId]/prompted-notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/books/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/books">> = Specific
  const handler = {} as typeof import("../../app/api/books/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/books/switch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/books/switch">> = Specific
  const handler = {} as typeof import("../../app/api/books/switch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/characters/[bookId]/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/[bookId]/[slug]">> = Specific
  const handler = {} as typeof import("../../app/api/characters/[bookId]/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/characters/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters/generate">> = Specific
  const handler = {} as typeof import("../../app/api/characters/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/characters/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/characters">> = Specific
  const handler = {} as typeof import("../../app/api/characters/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/home/currently-reading/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home/currently-reading">> = Specific
  const handler = {} as typeof import("../../app/api/home/currently-reading/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/home/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/home/stats">> = Specific
  const handler = {} as typeof import("../../app/api/home/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/notes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notes/[id]/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes/[id]/summary">> = Specific
  const handler = {} as typeof import("../../app/api/notes/[id]/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notes/recent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes/recent">> = Specific
  const handler = {} as typeof import("../../app/api/notes/recent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notes">> = Specific
  const handler = {} as typeof import("../../app/api/notes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reflection-change/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reflection-change">> = Specific
  const handler = {} as typeof import("../../app/api/reflection-change/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reflection-question/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reflection-question">> = Specific
  const handler = {} as typeof import("../../app/api/reflection-question/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
